# OpenAI Configuration
OPENAI_BASE_URL = "https://api.ai.it.cornell.edu/"
OPENAI_API_KEY = "sk-LD0PwlgBZFOcP_ZfbO_t-Q"

# Pinecone Configuration
PINECONE_API_KEY = "pcsk_3uwBWq_SYnVRhq3qCkCWjUAFCyfX9e8nhfmR6hyLfuejthRp5E7e2fYiue8h1sNTMxHegv"
PINECONE_ENV = "us-east1-gcp"
PINECONE_INDEX_NAME = "cornell-ai-hackathon-2025"

# AI Text Humanizer API Credentials
AI_HUMANIZER_EMAIL = "mbronik1@binghamton.edu"
AI_HUMANIZER_PASSWORD = "1LoveCor3LL!" 