# OpenAI Configuration
[openai]
api_key = "sk-LD0PwlgBZFOcP_ZfbO_t-Q"
base_url = "https://api.ai.it.cornell.edu/"

# Pinecone Configuration
[pinecone]
api_key = "pcsk_3uwBWq_SYnVRhq3qCkCWjUAFCyfX9e8nhfmR6hyLfuejthRp5E7e2fYiue8h1sNTMxHegv"
environment = "us-east1-gcp"
index_name = "cornell-ai-hackathon-2025"

# AI Text Humanizer Configuration
[humanizer]
email = "mbronik1@binghamton.edu"
password = "1LoveCor3LL!" 